server/python/routes/users.py
from flask import Blueprint, current_app, make_response, render_template, request, redirect, url_for, session
from domain.models import User
import domain.errors as err_codes
from domain.errors.messages import get_error_message
from routes import ensure_session

router = Blueprint('users', __name__)


@router.route('/login', methods=['GET'])
def login_form():
    return make_response(render_template('users/login.html'))


@router.route('/login', methods=['POST'])
def login_action():
    data = request.form.copy()
    message = None
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        User(data['user_name'], 'No Name', data['password'])  # Validate form data

        user, _id = current_app.config['USER_REPOSITORY'].by_login(data['user_name'], data['password'])
    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        session['session_id'] = _id

        return make_response(redirect(url_for('home')))

    return make_response(render_template(
        'users/login.html',
        user_name=data['user_name'],
        error=message,
    ))


@router.route('/register', methods=['GET'])
def register_form():
    return make_response(render_template('users/register.html'))


@router.route('/register', methods=['POST'])
def register_action():
    data = request.form.copy()
    message = None
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        user = User(data['user_name'], data['full_name'], data['password'])  # Validate form data

        current_app.config['USER_REPOSITORY'].create(user)
    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        return make_response(redirect(url_for('users.login_form')))

    return make_response(render_template(
        'users/register.html',
        user_name=data['user_name'],
        full_name=data['full_name'],
        error=message,
    ))


@router.route('/logout', methods=['GET'])
@ensure_session
def logout():
    session.clear()
    return make_response(redirect(url_for('home')))


@router.route('/profile', methods=['GET'])
@ensure_session
def profile_form():
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    return make_response(render_template('users/profile.html', user=user))


@router.route('/profile', methods=['POST'])
@ensure_session
def profile_action():
    data = request.form.copy()
    message = None
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        copy_user = User.load(user.export())
        if 'old_password' in data:
            assert data['new_password'] == data['confirm_new_password'], err_codes.PASSWORD_NOT_MATCH
            copy_user, _ = current_app.config['USER_REPOSITORY'].by_login(user.user_name, data['old_password'])
            copy_user.set_password(data['new_password'], data['old_password'])

        if 'user_name' in data:
            copy_user.user_name = data['user_name']

        if 'full_name' in data:
            copy_user.full_name = data['full_name']

    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        current_app.config['USER_REPOSITORY'].update(session['session_id'], copy_user)
        return redirect(url_for('home'))

    return make_response(render_template('users/profile.html', error=message, user=user))


@router.route('/view/<user_name>', methods=['GET'])
@ensure_session
def by_id(user_name: str):
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    _user = current_app.config['USER_REPOSITORY'].by_user_id(user_name)
    posts = current_app.config['POST_REPOSITORY'].filter(user_name, user_name)

    return make_response(render_template('users/by_id.html', user=user, _user=_user, posts=posts))

server/python/templates/users/by_id.html
{% extends "layouts/base.html" %}

{% set header = True %}
{% set title = "User @" + _user.user_name %}

{% block body %}
    <br>
    <div class="row is-center ">
        <div class="card col-8">
            <header>
                <h1 class="is-center">{{ _user.full_name | title }}&nbsp;<code>(@{{ _user.user_name }})</code></h1>
            </header>
        </div>
        <div class="col-6">
            <hr>
        </div>
        {% for post in posts %}
            {% include 'posts/card.html' %}
            <br>
        {% endfor %}

    </div>
{% endblock %}

server/python/templates/users/login.html
{% extends "layouts/base.html" %}
{% set title = "LogIn" %}

{% block body %}
    <br>
    <div class="row is-center ">
        <form accept-charset="{{ url_for('users.login_action') }}" method="POST" class="card col-4">
            <header class="is-center">
                <h1>LogIn</h1>
            </header>
            <div x-data="{showPassword: false}">
                {% if error %}
                    {% if error is string %}
                        <p style="color: var(--color-error);">{{ error }}</p>
                    {% else %}
                        <ul style="color: var(--color-error);">
                        {% for err in error %}
                        	<li>{{ err }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
                <p>
                    <label for="user_name">User Name</label>
                    <input required value="{{ user_name or '' }}" type="text" id="user_name" name="user_name" placeholder="HelloWorld">
                </p>
                <p>
                    <label for="password">Password</label>
                    <input required x-bind:type="showPassword? 'text' : 'password'" id="password" name="password" placeholder="S3cur3P455w0rd">
                </p>
                <p>
                    <label for="showPassword"><input x-on:click="showPassword = !showPassword" type="checkbox" id="showPassword"> Show password</label>
                </p>
                <p>
                    {{ form_security() }}
                </p>
                <p>
                    <a href="{{ url_for('users.register_form') }}">No account?, Register now!</a>
                </p>
            </div>
            <br>
            <footer class="is-right">
                <button class="button primary" type="submit">Submit</button>
                <button class="button" type="reset">Clear</button>
            </footer>
        </form>
    </div>
{% endblock %}

server/python/templates/users/profile.html
{% extends "layouts/base.html" %}

{% set header = True %}
{% set title = "Profile" %}

{% block body %}
    <br>
    <div class="row is-center">
        <form accept-charset="{{ url_for('users.profile_action') }}" method="POST" class="card col-4" x-data="{
            showPassword: false,
            userName: '{{ user.user_name or '' }}',
            editUserName: false,
            fullName: '{{ (user.full_name or '') | title }}',
            editFullName: false,
            editPassword: false,
        }">
            <header class="is-center">
                <h1>Update my profile</h1>
            </header>
            <div>
                {% if error %}
                    {% if error is string %}
                        <p style="color: var(--color-error);">{{ error }}</p>
                    {% else %}
                        <ul style="color: var(--color-error);">
                        {% for err in error %}
                        	<li>{{ err }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
                <p>
                    <label for="user_name">User Name</label>
                    <template x-if="editUserName">
                        <input required x-bind:value="userName" type="text" id="user_name" name="user_name" placeholder="HelloWorld">
                    </template>
                    <template x-if="!editUserName">
                        <div>
                                <input disabled x-bind:value="userName" type="text">
                            <button type="button" x-on:click="editUserName = true" style="margin-top: 1rem;" class="is-full-width button secondary">Edit</button>
                        </div>
                    </template>
                </p>
                <p>
                    <label for="full_name">Full Name</label>
                    <template x-if="editFullName">
                        <input required x-bind:value="fullName" type="text" id="full_name" name="full_name" placeholder="HelloWorld">
                    </template>
                    <template x-if="!editFullName">
                        <div>
                                <input disabled x-bind:value="fullName" type="text">
                            <button type="button" x-on:click="editFullName = true" style="margin-top: 1rem;" class="is-full-width button secondary">Edit</button>
                        </div>
                    </template>
                </p>
                <p>
                    <label for="oldPassword">Password</label>
                    <template x-if="editPassword">
                        <div>
                            <input required x-bind:type="showPassword? 'text' : 'password'" id="oldPassword" name="old_password" placeholder="Actual password">
                            <input style="margin-top: 1rem;" required x-bind:type="showPassword? 'text' : 'password'" id="newPassword" name="new_password" placeholder="New password">
                            <input required x-bind:type="showPassword? 'text' : 'password'" id="confirmNewPassword" name="confirm_new_password" placeholder="Confirm new password">
                        </div>
                    </template>
                    <template x-if="!editPassword">
                        <div>
                            <input disabled type="password" value="{{ '*' * 8 }}">
                            <button type="button" x-on:click="editPassword = true" style="margin-top: 1rem;" class="is-full-width button secondary">Edit</button>
                        </div>
                    </template>
                </p>
                <p x-show="editPassword">
                    <label for="showPassword"><input x-on:click="showPassword = !showPassword" type="checkbox" id="showPassword"> Show password</label>
                </p>
                <p>
                    {{ form_security() }}
                </p>
            </div>
            <br>
            <footer class="is-right">
                <button x-bind:disabled="!(editPassword || editFullName || editUserName)" class="button primary" type="submit">Submit</button>
            </footer>
        </form>
    </div>
{% endblock %}

server/python/templates/users/register.html
{% extends "layouts/base.html" %}
{% set title = "Register" %}

{% block body %}
    <br>
    <div class="row is-center ">
        <form accept-charset="{{ url_for('users.register_action') }}" method="POST" class="card col-4">
            <header class="is-center">
                <h1>Register</h1>
            </header>
            <div x-data="{showPassword: false}">
                {% if error %}
                    {% if error is string %}
                        <p style="color: var(--color-error);">{{ error }}</p>
                    {% else %}
                        <ul style="color: var(--color-error);">
                        {% for err in error %}
                        	<li>{{ err }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
                <p>
                    <label for="user_name">User Name</label>
                    <input required value="{{ user_name or '' }}" type="text" id="user_name" name="user_name" placeholder="HelloWorld">
                </p>
                <p>
                    <label for="full_name">Full Name</label>
                    <input required value="{{ full_name or '' }}" type="text" id="full_name" name="full_name" placeholder="Peter Parker">
                </p>
                <p>
                    <label for="password">Password</label>
                    <input required x-bind:type="showPassword? 'text' : 'password'" id="password" name="password" placeholder="S3cur3P455w0rd">
                </p>
                <p>
                    <label for="showPassword"><input x-on:click="showPassword = !showPassword" type="checkbox" id="showPassword"> Show password</label>
                </p>
                <p>
                    {{ form_security() }}
                </p>
                <p>
                    <a href="{{ url_for('users.login_form') }}">Already have an account?, Sign In!</a>
                </p>
            </div>
            <br>
            <footer class="is-right">
                <button class="button primary" type="submit">Submit</button>
                <button class="button" type="reset">Clear</button>
            </footer>
        </form>
    </div>
{% endblock %}