server/python/routes/posts.py
from flask import Blueprint, current_app, make_response, render_template, session, request, redirect, url_for
from domain.models import Post
from domain.errors.messages import get_error_message
import domain.errors as err_codes
from routes import ensure_session

router = Blueprint('posts', __name__)


@router.route('/', methods=['GET'])
@ensure_session
def home():
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    posts = current_app.config['POST_REPOSITORY'].list()
    return make_response(render_template(
        'posts/home.html',
        user=user,
        posts=posts,
    ))


@router.route('/create', methods=['GET'])
@ensure_session
def create_form():
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    return make_response(render_template(
        'posts/create.html',
        user=user,
    ))


@router.route('/create', methods=['POST'])
@ensure_session
def create_action():
    data = request.form.copy()
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])

    message = None

    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        content = data.get('content', None)
        if content == '':
            content = None

        post = Post(title=data['title'], content=content, user_name=user.user_name)
    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        current_app.config['POST_REPOSITORY'].create(post)
        return make_response(redirect(url_for('home')))

    return make_response(render_template(
        'posts/create.html',
        error=message,
        user=user,
    ))


@router.route('/view/<int:_id>', methods=['GET'])
@ensure_session
def by_id(_id: int):
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    post = current_app.config['POST_REPOSITORY'].by_id(_id)

    return make_response(render_template(
        'posts/by_id.html',
        user=user,
        post=post,
    ))

server/python/routes/users.py
from flask import Blueprint, current_app, make_response, render_template, request, redirect, url_for, session
from domain.models import User
import domain.errors as err_codes
from domain.errors.messages import get_error_message
from routes import ensure_session

router = Blueprint('users', __name__)


@router.route('/login', methods=['GET'])
def login_form():
    return make_response(render_template('users/login.html'))


@router.route('/login', methods=['POST'])
def login_action():
    data = request.form.copy()
    message = None
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        User(data['user_name'], 'No Name', data['password'])  # Validate form data

        user, _id = current_app.config['USER_REPOSITORY'].by_login(data['user_name'], data['password'])
    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        session['session_id'] = _id

        return make_response(redirect(url_for('home')))

    return make_response(render_template(
        'users/login.html',
        user_name=data['user_name'],
        error=message,
    ))


@router.route('/register', methods=['GET'])
def register_form():
    return make_response(render_template('users/register.html'))


@router.route('/register', methods=['POST'])
def register_action():
    data = request.form.copy()
    message = None
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        user = User(data['user_name'], data['full_name'], data['password'])  # Validate form data

        current_app.config['USER_REPOSITORY'].create(user)
    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        return make_response(redirect(url_for('users.login_form')))

    return make_response(render_template(
        'users/register.html',
        user_name=data['user_name'],
        full_name=data['full_name'],
        error=message,
    ))


@router.route('/logout', methods=['GET'])
@ensure_session
def logout():
    session.clear()
    return make_response(redirect(url_for('home')))


@router.route('/profile', methods=['GET'])
@ensure_session
def profile_form():
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    return make_response(render_template('users/profile.html', user=user))


@router.route('/profile', methods=['POST'])
@ensure_session
def profile_action():
    data = request.form.copy()
    message = None
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    try:
        token = data.get(current_app.config['FORM_SECURITY_PROVIDER'].get_target_key())
        assert current_app.config['FORM_SECURITY_PROVIDER'].validate(token), err_codes.FORBIDDEN

        copy_user = User.load(user.export())
        if 'old_password' in data:
            assert data['new_password'] == data['confirm_new_password'], err_codes.PASSWORD_NOT_MATCH
            copy_user, _ = current_app.config['USER_REPOSITORY'].by_login(user.user_name, data['old_password'])
            copy_user.set_password(data['new_password'], data['old_password'])

        if 'user_name' in data:
            copy_user.user_name = data['user_name']

        if 'full_name' in data:
            copy_user.full_name = data['full_name']

    except AssertionError as err:
        message = get_error_message(*err.args)
        message = f'{err.args[0]}: {message}'
    else:
        current_app.config['USER_REPOSITORY'].update(session['session_id'], copy_user)
        return redirect(url_for('home'))

    return make_response(render_template('users/profile.html', error=message, user=user))


@router.route('/view/<user_name>', methods=['GET'])
@ensure_session
def by_id(user_name: str):
    user = current_app.config['USER_REPOSITORY'].by_id(session['session_id'])
    _user = current_app.config['USER_REPOSITORY'].by_user_id(user_name)
    posts = current_app.config['POST_REPOSITORY'].filter(user_name, user_name)

    return make_response(render_template('users/by_id.html', user=user, _user=_user, posts=posts))

server/python/templates/posts/by_id.html
{% extends "layouts/base.html" %}

{% set header = True %}
{% set title = "Post #{:d}".format(post.id) %}

{% block body %}
    <br>
    <div class="row is-center ">
        <div class="card col-8">
            <header>
                <h1>{{ post.title }} - {{ post.date }}</h1>
                <a href="{{ url_for('users.by_id', user_name=post.user_name) }}">
                    <h3 style="color: var(--color-grey)">@{{ post.user_name }}</h3>
                </a>
            </header>
            {% if post.content %}
                <hr>
                <pre>{{ post.content }}</pre>
            {% endif %}
        </div>
    </div>
{% endblock %}

server/python/templates/posts/card.html
<div
        class="card col-8"
        x-data="{url: '{{ url_for('posts.by_id', _id=post.id) }}'}"
        x-on:click="location.href = url"
        style="cursor: pointer;"
>
    <header>
        <h2>{{ post.title }}</h2>
        <a href="{{ url_for('users.by_id', user_name=post.user_name) }}">
            <h6 style="color: var(--color-grey)">@{{ post.user_name }}</h6>
        </a>
    </header>
    {% if post.content %}
        <hr>
        <pre>{{ post.content }}</pre>
    {% endif %}
</div>

server/python/templates/posts/create.html
{% extends "layouts/base.html" %}

{% set header = True %}
{% set title = "New Post" %}

{% block body %}
    <br>
    <div class="row is-center ">
        <form accept-charset="{{ url_for('posts.create_action') }}" method="POST" class="card col-4">
            <header class="is-center">
                <h1>New Post</h1>
            </header>
            <div x-data="{showPassword: false}">
                {% if error %}
                    {% if error is string %}
                        <p style="color: var(--color-error);">{{ error }}</p>
                    {% else %}
                        <ul style="color: var(--color-error);">
                        {% for err in error %}
                        	<li>{{ err }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endif %}
                <p>
                    <label for="title">Title</label>
                    <input required type="text" id="title" name="title" placeholder="I'm great!">
                </p>
                <p>
                    <label for="content">Content (Optional)</label>
                    <textarea class="is-full-width" rows="10" id="content" name="content" placeholder="Something..."></textarea>
                </p>
                <p>
                    {{ form_security() }}
                </p>
            </div>
            <br>
            <footer class="is-right">
                <button class="button primary" type="submit">Submit</button>
                <button class="button" type="reset">Clear</button>
            </footer>
        </form>
    </div>
{% endblock %}

server/python/templates/posts/home.html
{% extends "layouts/base.html" %}

{% set header = True %}
{% set title = "Home" %}

{% block body %}
    <br>
    <div class="row is-center ">
        {% for post in posts %}
        	{% include 'posts/card.html' %}
            <br>
        {% endfor %}

    </div>
{% endblock %}